# Published Petstore 3 image from
# https://github.com/swagger-api/swagger-petstore
# (README: docker pull swaggerapi/petstore3:unstable).
#
# First `docker build` pulls that image if it is not already local.
# Later launches skip this file when the tagged image already exists.
FROM swaggerapi/petstore3:unstable

EXPOSE 8080
